apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: my-special-node
                  operator: In
                  values:
                    - "true"
      containers:
      - name: frontend-react
        image: mo1074/react:v3
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
